app/post_wall/models.py
from datetime import datetime
from app import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True)
    content = db.Column(db.String)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    def __repr__(self):
        return f'#{self.id} {self.name}: {self.content}'

app/dice_cal/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, SubmitField
from wtforms.validators import DataRequired

class ParameterForm(FlaskForm):
    dice = IntegerField('Number of dice', validators=[DataRequired()])
    side = IntegerField('Number of sides of each dice', validators=[DataRequired()])
    submit = SubmitField('Calculate')

app/post_wall/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from config import Config

from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

bootstrap = Bootstrap()
db = SQLAlchemy()
migrate = Migrate()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    bootstrap.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    from app.dice_cal import bp as dice_cal_bp
    app.register_blueprint(dice_cal_bp)
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    from app.post_wall import bp as post_wall_bp
    app.register_blueprint(post_wall_bp)


    return app

from app.main import routes
from app.post_wall import models

app/dice_cal/__init__.py
from flask import Blueprint

bp = Blueprint('dice_cal', __name__)

from app.dice_cal import main, routes

app/dice_cal/main.py
from decimal import Decimal

# deault precision of decimal package is 28, which is more than enough for our target precision for output (6 d.p.)
class TooManyCombinationsError(ValueError):
    """Exception raised for when the total number of possible combination of dice outcomes exceeded limit.

    Attributes:
        combination_n (int): The number of possible combinations from user input
        message (str): Error message
    """
    
    def __init__(self, combination_n: int, message: str="Number of possible cmobinations exceeded 10000", *args: object) -> None:
        self.combination_n = combination_n
        self.message = message
        super().__init__(self.message, *args)
        
    def __str__(self) -> str:
        return f"{self.combination_n} -> {self.message}"

def simulate(dice_n: int, side_n: int) -> dict[int,Decimal]:
    """Calculates the possibilities of every outcome of a given dice set by simulation. It is assumed that all dice are 
    prefectly fair and have same faces. Return a dictionary of outcomes and possibilitie or an error string when the 
    total number of possible instances is over 1000.

    Args:
        dice_n (int): the number of dice.
        side_n (int): the number of face of each dice.

    Returns:
        dict[int,Decimal]|str: dict with dice outcome as key and its possibility in percentage as value. If the total 
        number of possible instances is over 1000, an error message as string is returned instead.
    """

    case_count = side_n**dice_n
    if case_count > 10000:
        raise TooManyCombinationsError(case_count)

    min_face = 1
    max_face = side_n
    # create a dictionary of possible outcomes : number of instances
    outcome_range = range(min_face*dice_n, max_face*dice_n+1)
    outcome_instance_dict = dict.fromkeys(outcome_range, 0)
    
    # create a set of dice with min face
    dice_tray = [min_face] * dice_n
    
    # keep incrementing the dice until all combinations are iterated over
    while True:
        # if any die exceeds its max face, turn it back to min face
        for position, die in enumerate(dice_tray):
            if die > max_face:
                dice_tray[position] = min_face
                #increment the next die by 1
                dice_tray[position+1] += 1
                
        # calculate the sum of dice and add count to outcome_instance_dict
        outcome = sum(dice_tray)
        outcome_instance_dict[outcome] += 1
        
        # if all dice are at max face, break out from the loop
        if all(dice == max_face for dice in dice_tray):
            break
        # else increment the first dice by 1
        dice_tray[0] += 1
    
    # calculate the possibility of occurrence of an instance  
    inst_prob = Decimal(1)/case_count
    output = {outcome: round(count * inst_prob * 100, 6) for outcome, count in outcome_instance_dict.items()}
    return output

app/dice_cal/routes.py
from flask import render_template, request, render_template, url_for, jsonify, make_response
from flask import current_app

from app.dice_cal import bp
from app.dice_cal.forms import ParameterForm
from app.dice_cal.main import TooManyCombinationsError, simulate

@bp.route('/dice_cal', methods=['GET', 'POST'])
def main():
    form = ParameterForm()
    return render_template('dice_cal/main.html', title='Home', form=form)

@bp.route('/dice_cal/cal_sim', methods=['POST'])
def cal_sim():
    try:
        req = request.get_json()
    
        if req is None or req["dice"] == '' or req["side"] == '':
            return make_response(jsonify({"response_text": 'Invalid input'}), 400)
            
        dice_n = int(req["dice"])
        side_n = int(req["side"])
        result = simulate(dice_n, side_n)
        return make_response(jsonify({"result": result}), 200)
    
    except TooManyCombinationsError:
        return make_response(jsonify({"response_text": 'The number of possible combination exceeds 10000. Please try with smaller numbers.'}), 400)
    
    except:
        # catch all error response
        return make_response(jsonify({"response_text": 'The server has encountered an unexpected error.'}), 500)
    

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, request, render_template, url_for
from flask import current_app

from app.main import bp

@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html', title='Home')

app/post_wall/__init__.py
from flask import Blueprint

bp = Blueprint('post_wall', __name__)

from app.post_wall import routes, forms

app/post_wall/routes.py
from flask import render_template, request, render_template, url_for, redirect, flash
from flask import current_app

from app import db
from app.post_wall import bp
from app.post_wall.forms import PostForm
from app.post_wall.models import Post

from datetime import datetime

@bp.before_request
def before_request():
    db.session.commit()


@bp.route('/post_wall', methods=['GET', 'POST'])
def main():

    form = PostForm()
    
    if form.validate_on_submit():
        post = Post(name=form.name.data, content=form.content.data)
        db.session.add(post)
        db.session.commit()
        flash('Your Post is now on air!')
        return redirect(url_for('post_wall.main'))

    posts = Post.query.all()

    return render_template('post_wall/main.html', title='Post Wall', posts=posts, form=form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Lok Chan's Toolbox
    {% else %}Lok Chan's Toolbox
    {% endif %}
{% endblock title %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Toolbox</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('dice_cal.main') }}">Dice Calculator</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock navbar %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content are to be provided as block app_content #}
        {% block app_content %}
        
        {% endblock app_content %}
    </div>
{% endblock content %}

app/templates/dice_cal/main.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block scripts %}
    <script>

        function cal_sim() {
            var dice = document.getElementById("dice");
            var side = document.getElementById("side");
            var result = document.getElementById("result");

            var entry = {
                        dice: dice.value,
                        side: side.value
                        };

            fetch(`${window.origin}/dice_cal/cal_sim`, {
            method: "POST",
            credentials: "include",
            body: JSON.stringify(entry),
            cache: "no-cache",
            headers: new Headers({
                "content-type": "application/json"
            })
        })
            .then(function (response) {
                if (response.status !== 200) {
                    console.log(`Looks like there was a problem. Status code: ${response.status}`);
                    response.json().then(payload => {
                        result.innerHTML = `Status code: ${response.status} ${payload["response_text"]}`;
                    })
                    return;
                }
                response.json().then(function (data) {
                    //construct table
                    const result_HTML_list = Object.entries(data['result'])
                        .map(([outcome, prob]) => {
                            return `<tr><th scope:'row'>${outcome}</th><td>${prob}</td></tr>`
                        })
                    const tableHTML = result_HTML_list.join('')
                    result.innerHTML = tableHTML;
                });
            })
            .catch(function (error) {
                console.log("Fetch error: " + error);
            });
        }

    </script>
{% endblock scripts %}

{% block app_content %}
    <div class="container-fluid">
        <div class="row">
            <h1>Dice Probability Calculator</h1>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <label>Number of dice</label>
                    <input type="number" class="form-control" id="dice">
                </div>

                <div class="form-group">
                    <label>Number of sides</label>
                    <input type="number" class="form-control" id="side">
                </div>
                <br>
                <button class="btn btn-primary" id="calculate" onclick="cal_sim();">Calculate</button>
            </div>
            <div class="col-sm-8">
                <p>
                    Given the number of dice and the number of sides of the dice, the calculator simulates every possible
                    outcome and calculate the possibilties of getting each possible sum of dice with the assumption that
                    all the dice are fair. Results are displayed as percentages rounded to 6 decimal points.
                    
                    This uses a server-end function for simulation, so the input is throttled to 
                    prevent heavy load. The calculator will reject if the number of possible combination of dice exceeds
                    10000.
                </p>
            </div>
        </div>
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Outcome</th>
                        <th scope="col">Probability</th>
                    </tr>
                </thead>
                <tbody id="result">
                </tbody>
            </table>
        </div>
    </div>
{% endblock app_content %}

app/templates/index.html
{% extends 'base.html' %}

{% block app_content %}
<div class="container-fluid">
    <div class="row">
        <h1>Lok Chan's Toolbox</h1>
    </div>    
    <div class="row">
      <p>Welcome to my page! I am Lok Chan, a Linguistics and Data Science student currently in New Zealand.
        I started self-studying programming in 2019 Winter, and I work mainly with Python.

        This page hosts little things I built so to practice web application development.
      </p>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <a href="{{ url_for('dice_cal.main') }}">Dice Calculator</a>
      </div>
      <div class="col-sm-6">
        <a href="{{ url_for('post_wall.main') }}">Post Wall</a>
      </div>
    </div>
  </div>
{% endblock app_content %}

app/templates/post_wall/main.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
<h1>Post Wall</h1>
{% if posts %}
{% for post in posts %}
    <div class="container">
        <h5>{{ post.name }} says at {{ post.timestamp }}:</h5>
        <p>{{ post.content }}</p>
    </div>
{% endfor %}
{% endif %}

{% if form %}
{{ wtf.quick_form(form) }}
{% endif %}

{% endblock app_content %}